"""Tornei nome unico

Revision ID: ae3f8e2ff9fc
Revises: 5ada7c876953
Create Date: 2021-10-21 13:37:26.028739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3f8e2ff9fc'
down_revision = '5ada7c876953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_nome'), ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_nome'), type_='unique')

    # ### end Alembic commands ###
